version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      # ホストマシンのユーザーで volume を read only でマウントする
      # Thanks to https://qiita.com/yohm/items/047b2e68d008ebb0f001#%E3%81%86%E3%81%BE%E3%81%8F%E3%81%84%E3%81%8F%E6%96%B9%E6%B3%952--etcpasswd%E3%81%A8etcgroup%E3%82%92%E3%82%B3%E3%83%B3%E3%83%86%E3%83%8A%E3%81%AB%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88%E3%81%99%E3%82%8B
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - ./db/data:/var/lib/postgresql/data
      # データベースの初期化
      - ./db/init:/docker-entrypoint-initdb.d
